import { createFileRoute, Link } from "@tanstack/react-router";
import {
  Mail,
  FileText,
  CalendarCheck,
  Search,
  MessageSquare,
  ArrowRight,
  Sparkles,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Dashboard — AI Workplace Productivity Assistant" },
      { name: "description", content: "AI-powered workplace productivity dashboard" },
    ],
  }),
  component: Dashboard,
});

const tools = [
  {
    title: "Smart Email Generator",
    description: "Generate professional emails with the right tone and context.",
    icon: Mail,
    href: "/email",
    color: "text-primary",
    bg: "bg-primary/10",
  },
  {
    title: "Meeting Notes Summarizer",
    description: "Extract key decisions, action items, and deadlines from transcripts.",
    icon: FileText,
    href: "/meeting",
    color: "text-emerald",
    bg: "bg-emerald/10",
  },
  {
    title: "AI Task Planner",
    description: "Create prioritized daily, weekly, or monthly schedules.",
    icon: CalendarCheck,
    href: "/planner",
    color: "text-amber",
    bg: "bg-amber/10",
  },
  {
    title: "Research Assistant",
    description: "Research topics, compile summaries, and get actionable insights.",
    icon: Search,
    href: "/research",
    color: "text-slate",
    bg: "bg-slate/10",
  },
  {
    title: "AI Chatbot",
    description: "Get conversational help with any workplace productivity task.",
    icon: MessageSquare,
    href: "/chat",
    color: "text-primary",
    bg: "bg-primary/10",
  },
];

function Dashboard() {
  return (
    <div className="mx-auto max-w-5xl space-y-8">
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-primary-foreground">
            <Sparkles className="h-5 w-5" />
          </div>
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-foreground">
              Welcome to Workplace AI
            </h1>
            <p className="text-sm text-muted-foreground">
              Your AI-powered productivity assistant — choose a tool to get started.
            </p>
          </div>
        </div>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {tools.map((tool) => (
          <Link key={tool.href} to={tool.href}>
            <Card className="group h-full transition-all hover:shadow-md hover:border-primary/20">
              <CardHeader>
                <div
                  className={`mb-3 flex h-10 w-10 items-center justify-center rounded-lg ${tool.bg}`}
                >
                  <tool.icon className={`h-5 w-5 ${tool.color}`} />
                </div>
                <CardTitle className="text-base">{tool.title}</CardTitle>
                <CardDescription>{tool.description}</CardDescription>
              </CardHeader>
              <CardContent>
                <span className="inline-flex items-center text-sm font-medium text-primary group-hover:underline">
                  Open tool <ArrowRight className="ml-1 h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" />
                </span>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>

      <Card className="border-dashed">
        <CardContent className="py-6">
          <div className="flex flex-col items-center justify-center text-center">
            <div className="mb-3 rounded-full bg-muted p-3">
              <Sparkles className="h-5 w-5 text-muted-foreground" />
            </div>
            <h3 className="text-sm font-semibold text-foreground">
              AI-Powered Productivity
            </h3>
            <p className="mt-1 max-w-md text-xs text-muted-foreground">
              All content is generated by AI and should be reviewed before use in professional
              settings. We recommend fact-checking critical information.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
